[build]
  publish = "dist"
  command = "npm run build"

[dev]
  targetPort = 3000

[functions]
  # Increase timeout for voice processing functions (in seconds)
  timeout = "30s"
  # Allow larger file uploads for audio files
  max_content_length = "25MB"

[build.environment]
  # Enable Node.js 18 for better compatibility
  NODE_VERSION = "18"
